/*
Copyright (c) 2019-2026 Alexandr Kuzmuk

This file is part of the AsyncFw project. Licensed under the MIT License.
See {Link: LICENSE file https://mit-license.org} in the project root for full license information.
*/

#pragma once

/*! \example FunctionConnector/main.cpp FunctionConnector example */

#include "AbstractThread.h"

namespace AsyncFw {

class FunctionConnectionGuard;

/*! \class AbstractFunctionConnector FunctionConnector.h <AsyncFw/FunctionConnector> \brief The AbstractFunctionConnector class provides the base functionality for FunctionConnector
\exception std::runtime_error If the default connection type (AbstractFunctionConnector::ConnectionType) is DirectOnly, AutoOnly, or SyncOnly and there is a type mismatch when connecting (AbstractFunctionConnector::Connection::Type), the exception std::runtime_error("fixed connection type") will be raised. */
class AbstractFunctionConnector {
  friend FunctionConnectionGuard;

public:
  /*! \enum ConnectionType
  \brief Defines validation and behavior constraints for connections (e.g., forcing Direct or Queued modes). */
  enum ConnectionType : uint8_t { Auto = 0, Direct = 0x01, Queued = 0x02, Sync = 0x04, AutoOnly = 0x10, DirectOnly = 0x11, QueuedOnly = 0x12, SyncOnly = 0x14 };
  class Connection {
    friend AbstractFunctionConnector;
    friend FunctionConnectionGuard;

  public:
    /*! \enum Type
    \brief Specifies how the receiver slot should be invoked relative to the sender's thread. */
    enum Type : uint8_t { Auto = AbstractFunctionConnector::Auto, Direct = AbstractFunctionConnector::Direct, Queued = AbstractFunctionConnector::Queued, Sync = AbstractFunctionConnector::Sync, Default = 0x80 };

  protected:
    Connection(AbstractFunctionConnector *, Type);
    virtual ~Connection() = 0;
    AbstractThread *thread_;
    Type type_;

  private:
    AbstractFunctionConnector *connector_;
    FunctionConnectionGuard *guard_ = nullptr;
  };

  AbstractFunctionConnector(ConnectionType = Auto);

protected:
  template <typename F, typename... Args>
  class QueuedTask : public AbstractThread::AbstractTask {
  public:
    QueuedTask(F *f, Args &...args) : f_(f), args_(args...) {}
    ~QueuedTask() { delete f_; }
    void operator()() override { std::apply(*f_, args_); }
    F *f_;
    std::tuple<Args...> args_;
  };
  virtual ~AbstractFunctionConnector() = 0;
  std::vector<Connection *> list;
  ConnectionType defaultConnectionType;
  std::mutex mutex;
};

/*! \class FunctionConnector FunctionConnector.h <AsyncFw/FunctionConnector> \brief Provides a sender-to-receivers connection. Receivers can be invoked in their own threads (default behavior). Other tools typically implement this type of communication using callbacks. A callback is a function pointer; if you want a processing function to notify you about an event, you pass a pointer to another function (the callback) into it. The processing function then invokes the callback when necessary.
\brief FunctionConnector messages are generated by an object when its internal state changes in a way that might be of interest to other objects. FunctionConnector messages are public functions and can be emitted from anywhere, but it is highly recommended to emit them only from within the class that defines them. To restrict message emission to only one specific object type, use FunctionConnectorProtected instead.
\brief Example: \snippet FunctionConnector/main.cpp snippet */
template <typename... Args>
class FunctionConnector : public AbstractFunctionConnector {
public:
  using AbstractFunctionConnector::AbstractFunctionConnector;
  /*! \brief Connect a callable object (lambda, function pointer, functor) */
  template <typename T>
  Connection &connect(T f, Connection::Type t = Connection::Default) {
    std::lock_guard<std::mutex> lock(mutex);
#ifndef __clang_analyzer__
    return *new Connection(f, this, t);
#endif
  }
  /*! \brief Connect a class member method */
  template <typename M, typename O>
  Connection &connect(M m, O *o, Connection::Type t = Connection::Default) {
    std::lock_guard<std::mutex> lock(mutex);
#ifndef __clang_analyzer__
    return *new Connection(m, o, this, t);
#endif
  }
  /*! \brief Emit/Send the signal to all connected receivers */
  void operator()(Args... args) {
    std::lock_guard<std::mutex> lock(mutex);
    for (const Connection *c : *reinterpret_cast<std::vector<Connection *> *>(&list)) {
      if (!c->thread_) continue;
      if (c->type_ == Connection::Direct || (c->type_ != Connection::Queued && c->thread_->id() == std::this_thread::get_id())) {
        (c->f_)->invoke(args...);
        continue;
      }
      if (c->type_ != Connection::Sync) {
        AbstractThread::AbstractTask *_t = new QueuedTask(c->f_->copy(), args...);
        if (!c->thread_->invokeTask(_t)) delete _t;
      } else {
        c->thread_->invoke([c, &args...]() { (c->f_)->invoke(args...); }, true);
      }
    }
  }

protected:
  class Connection : public AbstractFunctionConnector::Connection {
    friend class FunctionConnector<Args...>;

  public:
    template <typename F>
    Connection(F &f, AbstractFunctionConnector *c, Type t) : AbstractFunctionConnector::Connection(c, t), f_(new Function(std::forward<F>(f))) {}
    template <typename M, typename O>
    Connection(M m, O *o, AbstractFunctionConnector *c, Type t) : AbstractFunctionConnector::Connection(c, t), f_(new MemberFunction(m, o)) {}

  private:
    struct AbstractFunction : public AsyncFw::Invocable<void(Args &...)>::Abstract {
      /*
      Invokes the target callable, guaranteeing COPY semantics for arguments.
      This method is explicitly used during immediate signal dispatching (Direct/Sync) within the loop.
      It passes arguments as plain lvalues, forcing the compiler to generate independent copies for each distinct receiver slot.
      The default operator() cannot be used for this purpose because it uses std::forward, which casts lvalues to rvalues (triggering move semantics).
      If operator() were called in a loop, the very first receiver would empty out (steal resources from) the arguments, leaving subsequent subscribers with moved-from, empty objects.
      */
      virtual void invoke(Args &...args) = 0;
      virtual AbstractFunction *copy() const = 0;
    };
    template <typename F>
    struct Function : AbstractFunction {
      Function(F &&f) : f_(std::forward<F>(f)) {}
      Function(const Function *f) : f_(f->f_) {}
      void operator()(Args &...args) override { f_(std::forward<Args>(args)...); }
      void invoke(Args &...args) override { f_(args...); }
      AbstractFunction *copy() const override { return new Function(this); }
      F f_;
    };
    template <typename M, typename O>
    struct MemberFunction : AbstractFunction {
      MemberFunction(M m, O *o) : m_(m), o_(o) {}
      MemberFunction(const MemberFunction *f) : m_(f->m_), o_(f->o_) {}
      void operator()(Args &...args) override { (o_->*m_)(std::forward<Args>(args)...); }
      void invoke(Args &...args) override { (o_->*m_)(args...); }
      AbstractFunction *copy() const override { return new MemberFunction(this); }
      M m_;
      O *o_;
    };
    ~Connection() override { delete f_; }
    AbstractFunction *f_;
  };
};

/*! \class FunctionConnectorProtected FunctionConnector.h <AsyncFw/FunctionConnector> \brief A protected connector where only a single designated sender can emit messages.
\copybrief FunctionConnector \brief Example: \snippet FunctionConnector/main.cpp snippet */
template <typename F>
class FunctionConnectorProtected {
public:
  template <typename... Args>
  class Connector : private FunctionConnector<Args...> {
    friend F;

  public:
    using FunctionConnector<Args...>::FunctionConnector;
    using FunctionConnector<Args...>::connect;

  protected:
    using FunctionConnector<Args...>::operator();
  };
};

/*! \class FunctionConnectionGuard FunctionConnector.h <AsyncFw/FunctionConnector> \brief The FunctionConnectionGuard class.
\brief Disconnects the connection automatically upon destruction (RAII). */
class FunctionConnectionGuard {
  friend AbstractFunctionConnector::Connection;

public:
  FunctionConnectionGuard();
  FunctionConnectionGuard(FunctionConnectionGuard &&);
  FunctionConnectionGuard(AbstractFunctionConnector::Connection &);
  ~FunctionConnectionGuard();
  void operator=(AbstractFunctionConnector::Connection &);
  void operator=(FunctionConnectionGuard &&);
  operator bool() const { return c_; }

private:
  AbstractFunctionConnector::Connection *c_;
  void destroyConnection();
};

/*! \class FunctionConnectionGuardList \brief A helper container that manages multiple FunctionConnectionGuard lifecycles simultaneously. */
class FunctionConnectionGuardList : public std::vector<FunctionConnectionGuard> {
public:
  /*! \brief Appends a moving connection guard to the management list. */
  void operator+=(FunctionConnectionGuard &&);
};
}  // namespace AsyncFw
