if(VERSION_STRING)
  return()
endif()

set(VERSION_STRING 1.2.4)

if(NOT EXISTS ${CMAKE_CURRENT_BINARY_DIR}/version)
  execute_process(COMMAND ${CMAKE_COMMAND} -DSOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR} -DBINARY_DIR=${CMAKE_CURRENT_BINARY_DIR} -P ${CMAKE_CURRENT_LIST_DIR}/version.script.cmake)
endif()

file(READ ${CMAKE_CURRENT_BINARY_DIR}/version GIT_VERSION)

string(REGEX MATCH
  ".*/(v|(.*)-)([(0-9)]*[.][(0-9)]*[.][(0-9)]*)-([0-9]*)-g[a-f 0-9]*((-m)?)$" _
  ${GIT_VERSION})

if(CMAKE_MATCH_1)
  set(VERSION_STRING "${CMAKE_MATCH_3}")
  set(VERSION_STRING "${VERSION_STRING}.${CMAKE_MATCH_4}")
endif()

set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_BINARY_DIR}/version")
add_custom_target(app-version
  BYPRODUCTS "${CMAKE_CURRENT_BINARY_DIR}/version"
  COMMAND ${CMAKE_COMMAND} -DSOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR} -DBINARY_DIR=${CMAKE_CURRENT_BINARY_DIR} -DGENERATOR=${CMAKE_GENERATOR} -P ${CMAKE_CURRENT_LIST_DIR}/version.script.cmake
  COMMENT "update version")

message("GIT_VERSION: ${GIT_VERSION}, VERSION: ${VERSION_STRING}")

set(VH "#pragma once
#define GIT_VERSION \"${GIT_VERSION}\"
#define VERSION_STRING \"${VERSION_STRING}\"
")
if(EXISTS "${CMAKE_CURRENT_BINARY_DIR}/version.hpp")
  file(READ "${CMAKE_CURRENT_BINARY_DIR}/version.hpp" STR)
endif()
if(NOT VH STREQUAL STR)
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/version.hpp" "${VH}")
endif()
