if(VERSION_STRING)
  return()
endif()

set(VERSION_STRING 1.0.0)

execute_process(
  COMMAND ${CMAKE_COMMAND} -DSOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR} -DBINARY_DIR=${CMAKE_CURRENT_BINARY_DIR} -P ${CMAKE_CURRENT_LIST_DIR}/version.script.cmake)

file(READ ${CMAKE_CURRENT_BINARY_DIR}/version GIT_VERSION)

string(REGEX MATCH
  ".*/(v|(.*)-)([(0-9)]*[.][(0-9)]*[.][(0-9)]*)-([0-9]*)-g[a-f 0-9]*((-m)?)$" _
  ${GIT_VERSION})

if(CMAKE_MATCH_1)
  set(VERSION_STRING "${CMAKE_MATCH_3}")
  set(VERSION_STRING "${VERSION_STRING}.${CMAKE_MATCH_4}")
endif()

set_property(
  DIRECTORY
  APPEND
  PROPERTY CMAKE_CONFIGURE_DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/version)

add_custom_target(
  app-version ALL
  COMMAND ${CMAKE_COMMAND} -DSOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR} -DBINARY_DIR=${CMAKE_CURRENT_BINARY_DIR} -DGENERATOR=${CMAKE_GENERATOR} -P ${CMAKE_CURRENT_LIST_DIR}/version.script.cmake
  BYPRODUCTS "${CMAKE_CURRENT_BINARY_DIR}/version")

message("GIT_VERSION: ${GIT_VERSION}, VERSION: ${VERSION_STRING}")
